project_id = "zcrnfrijqasbrjrxconi"

[functions.prerender-story]
verify_jwt = false

[functions.prerender-post]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.prerender-marketing]
verify_jwt = false

[functions.clickmeeting-register]
verify_jwt = false

[functions.clickmeeting-list-conferences]
verify_jwt = false

[functions.llms-txt]
verify_jwt = false

[functions.translate-story]
verify_jwt = false

[functions.translate-post]
verify_jwt = false
