// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published Quantifier.ai blog posts, optionally filtered by locale (en, pl, cs).",
  inputSchema: {
    locale: z.enum(["en", "pl", "cs"]).optional().describe("Language filter."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ locale, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("posts").select("id, title, slug, excerpt, locale, published_at").eq("status", "published").order("published_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (locale) query = query.eq("locale", locale);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-case-studies.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_case_studies_default = defineTool2({
  name: "list_case_studies",
  title: "List case studies",
  description: "List published Quantifier.ai customer case studies (success stories).",
  inputSchema: {
    locale: z2.enum(["en", "pl", "cs"]).optional().describe("Language filter."),
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum stories to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ locale, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("stories").select("id, title, slug, excerpt, locale, published_at, created_at").eq("status", "published").order("published_at", { ascending: false, nullsFirst: false }).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (locale) query = query.eq("locale", locale);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { stories: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "quantifier-ai-mcp",
  title: "Quantifier.ai MCP",
  version: "0.1.0",
  instructions: "Read-only access to Quantifier.ai public marketing content. Use `list_blog_posts` for published blog articles and `list_case_studies` for customer success stories. Both accept an optional `locale` (en, pl, cs).",
  tools: [list_blog_posts_default, list_case_studies_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
